version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:4000
    platform: linux/x86_64
    volumes:
      - .:/code
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:13.1
    environment:
      POSTGRES_DB: "postgres_bitcoin"
      POSTGRES_USER: "postgres_bitcoin"
      POSTGRES_PASSWORD: "postgres_bitcoin"
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data:
